version: "3.8"

services:
  springboot:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080
    restart: always
    expose:
      - "8080"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8001:80"  # ⚡️ Render dùng HTTP, nên map vào 80 thay vì 10000
    depends_on:
      - springboot
    restart: always  # ⚡️ Đảm bảo Nginx không bị dừng
    networks:
      - my_network

networks:
  my_network:
