version: "3.8"

services:
  springboot:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080  # Cổng Render cấp động
    restart: always
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "10000:10000"
    depends_on:
      - springboot
    environment:
      - BACKEND_HOST=springboot
      - BACKEND_PORT=8080
