services:
  - name: springboot
    type: web
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon

  - name: nginx
    type: web
    runtime: docker
    envVars:
      - key: PORT
        value: "10000"  # Nếu cần, Render sẽ cấp giá trị này
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    region: oregon
