services:
  - name: springboot
    type: web
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: PORT
        value: "8080"  # ⚡️ Bắt buộc Spring Boot lắng nghe đúng port
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon

  - name: nginx
    type: web
    runtime: docker
    envVars:
      - key: PORT
        value: "80"  # ⚡️ Render luôn sử dụng port 80 cho HTTP
      - key: BACKEND_HOST
        value: "springboot"
      - key: BACKEND_PORT
        value: "8080"
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    region: oregon
