services:
  - name: springboot
    type: web
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon

  - name: nginx
    type: web
    runtime: docker
    envVars:
      - key: BACKEND_HOST
        value: "springboot"
      - key: BACKEND_PORT
        value: "8080"
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    region: oregon
